import Head from 'next/head'
import Topbar from '../components/Topbar/Topbar'
import Main from '../components/Main/Main'
import {Quotes} from '../Data/Quotes'
import styles from '../styles/Home.module.css'
import HomeScreen from '../components/HomeScreen'

export default function Home() {
  console.log(Quotes);
  return (
      <div className={styles.container}>
        <Head>
          <title>Motivation</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HomeScreen />

        <footer className={styles.footer}>
            Powered by istiak
        </footer>
      </div>

  )
}
