import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header/Header'
import Topbar from '../components/Topbar/Topbar'
import Main from '../components/Main/Main'
import {Quotes} from '../Data/Quotes'
import styles from '../styles/Home.module.css'

export default function Home() {
  console.log(Quotes);
  return (
    <div className={styles.container}>
      <Head>
        <title>Motivation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Topbar />
      
      <Main quotes={Quotes} />

      <footer className={styles.footer}>
          Powered by Istiak
      </footer>
    </div>
  )
}
